### ISSUE TITLE
Investigate default `ralph.json` in ralph home folder

### ISSUE THREAD

**Issue by tdroxler** [alephium/ralph-lsp#214]
If no `ralph.json` is found in project, we could fallback to a default one inside the `RALPH_LSP_HOME`.

This would help the new users, but it might introduce other problems as discussed [here](https://github.com/alephium/ralph-lsp/pull/211#issuecomment-2141342344)

**Comment by tdroxler** [comment]
some default values are defined in web3 :
* https://github.com/alephium/alephium-web3/blob/8a1df0c37a66a6f79bdd9fb05d24bea260462db6/packages/web3/src/contract/contract.ts#L110-L117
* https://github.com/alephium/alephium-dex/blob/master/alephium.config.ts#L29-L32

we have the web3 files available, but not sure we could extract those information from those TS file. I'll dig a bit

**Comment by tdroxler** [comment]
### Configuration Management in `ralph-lsp`

#### Current State
The `ralph-lsp` project stores configuration details in `ralph.json`, including:
- `compilerOptions`
- `contractPath`
- `artifactPath`
- `dependencyPath`

[View source](https://github.com/alephium/ralph-lsp/blob/c86138485fc49eb1080f511da2ce4ec011ed3363/presentation-compiler/src/main/scala/org/alephium/ralph/lsp/pc/workspace/build/RalphcConfig.scala#L44-L48)

Only `dependencyPath` is specific to `ralph-lsp`. The other three options are also used by the web3 project for compiling/deploying through the node, stored in `alephium.config.ts` within the [Configuration interface](https://github.com/alephium/alephium-web3/blob/81797fbce5ee2af358410a3f5dd8dfe5bd5b7682/packages/cli/src/types.ts#L46-L60).

When `ralph-lsp` starts in a project without `ralph.json`, an error prompts the user to create that file. 

Since all Ralph developers already have `alephium.config.ts`, requiring them to maintain compiler options in two files is not viable.

#### Requirements
To streamline this process, we propose the following:
1. **Extract Compiler Configurations from TS File**: Avoid duplication by extracting configurations from the TypeScript file.
2. **Move LSP-related Configurations**: Shift `ralph-lsp` specific configurations to `.ralph-lsp` folder with default values to simplify its usage, avoid errors for new developers and increase adoption.

Extraction from TS can be achieved with [fastparse](https://github.com/alephium/ralph-lsp/commit/c86138485fc49eb1080f511da2ce4ec011ed3363), instead of deserializing a JSON file into Scala with upickle.

@simerplaha requesting your feedback on this, thx

**Comment by simerplaha** [comment]
Hey @tdroxler, 

Just to re-confirm: This suggests that we extract `compilerOptions`, `contractPath` and `artifactPath` from [`alephium.config.ts`](https://docs.alephium.org/sdk/cli/#configuration) right? Because the above [fastparse](https://github.com/alephium/ralph-lsp/commit/c86138485fc49eb1080f511da2ce4ec011ed3363) code extracts `compilerOptions` from a `contract.ts` file in web3.

### Question 1 for Requirement 1 - Extract Compiler Configurations from TS File

Since the [configuration](https://docs.alephium.org/sdk/cli/#configuration) we want to parse using fastparse is regular TypeScript code, we are kinda restricting devs to use constants for these settings. For example, if they want to configure it via environment variables or some complex function calls, they won't be able to, as the parser expects constants.

**Comment by tdroxler** [comment]
From the `contracts.ts` we extract the [default compiler options](https://github.com/alephium/alephium-web3/blob/ff1569fc2ed05de7e0a19236910d2050acbcca36/packages/web3/src/contract/contract.ts#L110), then from `alephium.config.ts` we need to extract optional [compiler options](https://github.com/alephium/alephium-web3/blob/ff1569fc2ed05de7e0a19236910d2050acbcca36/packages/cli/src/types.ts#L53) that can override the default ones, each [compiler option is optional](https://github.com/alephium/alephium-web3/blob/ff1569fc2ed05de7e0a19236910d2050acbcca36/packages/web3/src/api/api-alephium.ts#L490-L498).

So my current idea was to extract once the default values and then we watch `alephium.confif.ts` and check if some `compilerOptions` are defined and/or changed.

Now you raised a very good point, we indeed won't be able to manage any kind of values that aren't just plain constants...

Default values could still be extracted from web3, even at compile time and stored into `/resources`. So at least user can start using ralph-lsp without having to configure something.

But for the "live" config, I don't have yet a solution. I see two directions:
1. Web3 defines everything compiler related stuff in `ralph.json` file and import that file in `alephium.config.ts`
  pro: ralph-lsp can watch that json file  
  cons: There are 2 files for configuration (but in a sense it make a clear separation between compiler and sdk)

2. When web3 compiles, it outputs a json file with the values defined in `alephium.config.ts`
  pro: Only 1 configuration file
  cons: ralph-lsp will reflect the compiling changes only when user compile the project with web3.  

None are ideal, I'll try to think more about it.

Do you have any proposition?

**Comment by simerplaha** [comment]
> From the contracts.ts we extract the [default compiler options](https://github.com/alephium/alephium-web3/blob/ff1569fc2ed05de7e0a19236910d2050acbcca36/packages/web3/src/contract/contract.ts#L110),

Can we use [node](https://github.com/alephium/alephium/blob/feda3788061beb12dbc5f1216d33f5d9d30f076d/ralph/src/main/scala/org/alephium/ralph/CompilerOptions.scala#L29-L35) instead as it's simpler to do? Or is it important that we extract default compiler options from web3?

> I see two directions:

Your first suggestion for having compiler related stuff in `ralph.json` file sounds good. It would also be the standard approach following `Cargo.toml`, `package.json` etc.

Two or more systems want to share some configuration data so using a shared configuration file makes sense and is simple.

## Question 2 for Requirement 2 - Move LSP-related Configurations

> Shift `ralph-lsp` specific configurations to `.ralph-lsp` folder with default values to simplify its usage, avoid errors for new developers and increase adoption.

Considering issue #44 implementing library support: If we move `ralph-lsp` specific configurations to the home/common folder `.ralph-lsp` then wouldn't all configured `dependencies` in that config file be downloaded, parsed and compiled for every project? Even for the ones that do not require any dependency? This would increase boot-up and compile time.

```json
{
  "compilerOptions":  {...},
  "contractPath": "...",
  "artifactPath": "...",
  "dependencyPath": "...",
  "dependencies": {
    "web3": "0.38.0",
    "ralph-test": "0.0.0",
    "data-structures": "0.0.0"
  }
}
```

**Comment by tdroxler** [comment]
>Can we use [node](https://github.com/alephium/alephium/blob/feda3788061beb12dbc5f1216d33f5d9d30f076d/ralph/src/main/scala/org/alephium/ralph/CompilerOptions.scala#L29-L35) instead as it's simpler to do? Or is it important that we extract default compiler options from web3? 

Oh I didn't know we had default one in node, I guess we could. I'll confirm with the node team once we have a clear vision on everything, if we can guarantee that node and web3 always have the same default value,  I think we'll be good.

> Question 2

I was unclear sorry (still a bit messy in my head too ^^) this time I was thinking of having a `.ralph-lsp` inside every project, but it's true that the first comment in this issue was mentioning home folder.

As you said it won't make sense to have those in the home folder.

## Next Move

* I will check with web3 team their opinion on having a `ralph.json` file

**Comment by simerplaha** [comment]
Closing as resolved.
