### ISSUE TITLE
Unused variables warnings for TxScript

### ISSUE THREAD

**Issue by raduciobanu22** [alephium/ralph-lsp#232]
I'm getting unused variables warnings for all my TxScripts.
For example:
```
TxScript CancelOffer(marketplace: LendingMarketplace, offerId: ByteVec) {
  marketplace.cancelOffer(offerId)
}
```
And the warning:
```
[{
	"resource": "",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Found unused fields in CancelOffer: marketplace, offerId",
	"source": "RalphLSP",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

VSCode: 1.90.2
Ralph LSP: v0.1.17

**Comment by tdroxler** [comment]
what's the return type of your `cancelOffer`? 

It's actually the node that returns the warnings, for example with this very small example:
```
Contract Market() {
  pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}
}

TxScript CancelOffer(market: Market, offerId: ByteVec) {
  market.cancelOffer(offerId)
}
```
if you call the node directly:

```
curl -s -X 'POST' 'https://node.mainnet.alephium.org/contracts/compile-project' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "code": "Contract Market() {\n pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}\n }\n\n TxScript CancelOffer(market: Market, offerId: ByteVec) {\n market.cancelOffer(offerId)\n }"
}' \
| jq '.scripts | map(.warnings)'

**Comment by tdroxler** [comment]
what's the return type of your cancelOffer?

It's actually the node that returns the warnings, for example with this very small example:
```rust
Contract Market() {
  pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}
}

TxScript CancelOffer(market: Market, offerId: ByteVec) {
  market.cancelOffer(offerId)
}
```
if you call the node directly:
```bash
curl -s -X 'POST' 'https://node.mainnet.alephium.org/contracts/compile-project' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "code": "Contract Market() {\n pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}\n }\n\n TxScript CancelOffer(market: Market, offerId: ByteVec) {\n market.cancelOffer(offerId)\n }"
}' \
| jq '.scripts | map(.warnings)'

[
  [
    "The return values of the function \"Market.cancelOffer\" are not used. If this is intentional, consider using anonymous variables to suppress this warning."
  ]
]
```

As suggested by the warning, you can disable the warning with a anonymous variable:

```
let _ =  market.cancelOffer(offerId)  // ignore the return value
```

But we'll see if we can add a compiler options to disable this warning.

**Comment by tdroxler** [comment]
@raduciobanu22 If it's not that case, can you provide a minimal example to reproduce your error?

Thanks a lot

**Comment by tdroxler** [comment]
Ok we reproduced it here https://github.com/Lbqds/unused-fields-warning

But that's very strange, at first the warning isn't there, but it appears as soon as we do a `npx @alephium/cli compile --debug`.

I'll dig in that direction.

**Comment by simerplaha** [comment]
> But that's very strange, at first the warning isn't there, but it appears as soon as we do a npx @alephium/cli compile --debug.

Could this issue be related to the one described in #61 (Inconsistent warnings) with [test code](https://github.com/alephium/ralph-lsp/issues/61#issuecomment-1926296839) to replicate it?

**Comment by raduciobanu22** [comment]
> > But that's very strange, at first the warning isn't there, but it appears as soon as we do a npx @alephium/cli compile --debug.
> 
> Could this issue be related to the one described in #61 (Inconsistent warnings) with [test code](https://github.com/alephium/ralph-lsp/issues/61#issuecomment-2204738829) to replicate it?

It's somewhat similar I guess. If I save the file, the warning goes away but shows up again once I open that file again or save another one.

**Comment by raduciobanu22** [comment]
> what's the return type of your cancelOffer?
> 
> It's actually the node that returns the warnings, for example with this very small example:
> 
> ```rust
> Contract Market() {
>   pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}
> }
> 
> TxScript CancelOffer(market: Market, offerId: ByteVec) {
>   market.cancelOffer(offerId)
> }
> ```
> 
> if you call the node directly:
> 
> ```shell
> curl -s -X 'POST' 'https://node.mainnet.alephium.org/contracts/compile-project' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "code": "Contract Market() {\n pub fn cancelOffer(b:ByteVec) -> ByteVec {return b}\n }\n\n TxScript CancelOffer(market: Market, offerId: ByteVec) {\n market.cancelOffer(offerId)\n }"
> }' \
> | jq '.scripts | map(.warnings)'
> 
> [
>   [
>     "The return values of the function \"Market.cancelOffer\" are not used. If this is intentional, consider using anonymous variables to suppress this warning."
>   ]
> ]
> ```
> 
> As suggested by the warning, you can disable the warning with a anonymous variable:
> 
> ```
> let _ =  market.cancelOffer(offerId)  // ignore the return value
> ```
> 
> But we'll see if we can add a compiler options to disable this warning.

That method returns `()`.

**Comment by tdroxler** [comment]
thx @raduciobanu22 I think we found the source of the issue, we'll keep you updated once it's fixed.

**Comment by tdroxler** [comment]
@raduciobanu22 https://github.com/alephium/ralph-lsp/pull/235 should fix it

**Comment by tdroxler** [comment]
Fixed in https://github.com/alephium/ralph-lsp/releases/tag/v0.1.19

**Comment by raduciobanu22** [comment]
@tdroxler Just tested 0.1.19 and the warnings are gone. Nice job!
