### ISSUE TITLE
Error: artifacts folder does not exit

### ISSUE THREAD

**Issue by polarker** [alephium/ralph-lsp#247]
Got this error while developing a new project. We should not require the existence of `artifacts` folder

<img width="440" alt="Screenshot 2024-07-27 at 16 51 20" src="https://github.com/user-attachments/assets/91c8ae56-7cc9-4c66-9695-cef19bfc7ef2">

**Comment by simerplaha** [comment]
Resolved in the above attached PR. Please let me know if you are ok with it being optional for now. Implementing deployment in #84 may or may not require `artifactsPath`, if not required, it can be removed then.

**Comment by polarker** [comment]
> Resolved in the above attached PR. Please let me know if you are ok with it being optional for now. Implementing deployment in #84 may or may not require `artifactsPath`, if not required, it can be removed then.

Thanks!
