### ISSUE TITLE
Optional `compilerOptions`

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#271]
Latest version of `ralphc` introduced a new compiler option: `"ignoreUnusedFunctionReturnWarnings": false`. If we release from master now, existing projects will get the error `missing keys in dictionary: ignoreUnusedFunctionReturnWarnings`. 

Should we make `compilerOptions` optional before releasing, so that the above error does not occur?

Default `compilerOptions` being [`CompilerOptions.Default`](https://github.com/alephium/alephium/blob/b78170a4bd2cc648c84a747623cbe1cc37250dba/ralph/src/main/scala/org/alephium/ralph/CompilerOptions.scala#L30).

@tdroxler

**Comment by tdroxler** [comment]
Yes, totally fine for me.

We want to have smooth update of `ralph-lsp` for users, otherwise we can be sure someone will open an issue about this error
