### ISSUE TITLE
Ralph-LSP doesn't completely stop 

### ISSUE THREAD

**Issue by tdroxler** [alephium/ralph-lsp#310]
Some instances keep running, we need to make sure ralph-lsp is well stop.

![image](https://github.com/user-attachments/assets/3b05f337-8cf2-4f14-ac50-d20ede645d98)

**Comment by simerplaha** [comment]
An older issue #37 already exists.

**Comment by simerplaha** [comment]
# Documenting Replication Attempts

I've tried replicating this by causing abrupt shutdowns which disallows LSP client (VSCode) to execute proper closing APIs with `shutdown` and then `exit` (visible in the logs). In these cases, all Java processes always terminate exactly after 1 minute ([seen before](https://github.com/alephium/ralph-lsp/issues/37#issuecomment-1770168496)). I'm seeing this same behaviour over several attempts, for all instances, with the deployed VSCode plugin and also locally in dev mode. Even if the `System.exit` call is removed from the `exit` API, the processes always terminate exactly after 1 minute.

![image](https://github.com/user-attachments/assets/b79c81af-55a4-47f6-8a4a-8cd55080fd06)

I've tried to replicate the similar 1 minute shutdown delay behaviour on Metals with similar tests, and the bloop server does not seem to terminate at all. I've caught this 3 times over several attempts. The Java processes were alive for 5-15 minutes before I manually terminated them.

![image](https://github.com/user-attachments/assets/c18fc2ff-1c1d-4e1d-960e-5f308ad41910)
![image](https://github.com/user-attachments/assets/914019dd-e902-4410-b620-ef4b8df5eadd)
![image](https://github.com/user-attachments/assets/1a66c384-6f51-4226-82e6-07d4f3fe0053)

**Comment by tdroxler** [comment]
Thx for the investigation. 

Maybe we could re-take from the previous task:

- [ ] Investigation as to why Java future times out after exactly 1 minute, 65-70 seconds to be exact.

If we can show from the documentation that it's an expected behavior, I think we should be fine. 

Maybe we could also do the same test with https://github.com/redhat-developer/vscode-java and see if we see the same 1 minute?

**Comment by simerplaha** [comment]
As assumed [here](https://github.com/alephium/ralph-lsp/issues/37#issuecomment-1770168496), the timeout is configured in Java land. LSP4J uses the [cachedThreadPool](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/concurrent/Executors.java#L216-L219) which defaults to 60 seconds. A custom thread-pool with reduced timeout terminates it earlier. 

```scala
val threadPool =
  new ThreadPoolExecutor(
    0, Integer.MAX_VALUE,
    30L, TimeUnit.SECONDS,
    new SynchronousQueue[Runnable]
  )
```
