### ISSUE TITLE
Server not stopped when editor exit

### ISSUE THREAD

**Issue by tdroxler** [alephium/ralph-lsp#37]
After exiting the editor, the java process is still running.

On first image we see that the server is not running
![image](https://github.com/alephium/ralph-lsp/assets/2979182/6dc29b25-48be-4948-9741-e3ff376dca96)

Then the process is running when editor is launched
![image](https://github.com/alephium/ralph-lsp/assets/2979182/14be51af-7de0-41ce-8777-ae2186b36928)

When exiting process is still there, also showing that editor process is not running
![image](https://github.com/alephium/ralph-lsp/assets/2979182/565dad50-d9c3-4d33-a1f2-e9c9d3ad467d)

**Comment by simerplaha** [comment]
Further progress is documented in the newer issue #310.
