### ISSUE TITLE
Error should report invalid import statement

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#43]
Error message can be improved. It should report invalid import statement rather than "Expecting a `Script`, `Contract` or `Interface`".

![image](https://github.com/alephium/ralph-lsp/assets/1773953/09a99762-a0e8-430a-8526-3a4b415742e2)

**Comment by tdroxler** [comment]
![image](https://github.com/alephium/ralph-lsp/assets/2979182/d10f2a92-fb0a-431f-ae4f-d5aedb623895)
![image](https://github.com/alephium/ralph-lsp/assets/2979182/6ba084c7-e81e-47fc-a0ba-65fc7cc69d82)
I think this is fixed
