### ISSUE TITLE
File header for source-files

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#45]
Add file header to source-files. 

Copying backend-explorer.

> // Copyright 2018 The Alephium Authors
// This file is part of the alephium project.
//
// The library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the library. If not, see <http://www.gnu.org/licenses/>.

@tdroxler is this right according to the licensing and all? Still LGPL3.0?

**Comment by tdroxler** [comment]
I (finally) checked with the team ^^ it's all good to use that one, we can just use 2024 instead of 2018.

we can easily do it on all our `*.scala` file with that command: 
```
find -name "*.scala" | xargs sed -i '1i\
// Copyright 2024 The Alephium Authors\
// This file is part of the alephium project.\
//\
// The library is free software: you can redistribute it and/or modify\
// it under the terms of the GNU Lesser General Public License as published by\
// the Free Software Foundation, either version 3 of the License, or\
// (at your option) any later version.\
//\
// The library is distributed in the hope that it will be useful,\
// but WITHOUT ANY WARRANTY; without even the implied warranty of\
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\
// GNU Lesser General Public License for more details.\
//\
// You should have received a copy of the GNU Lesser General Public License\
// along with the library. If not, see http://www.gnu.org/licenses/.\
'
```

Maybe it's better if you do it otherwise I'll become the main contributor in one commit :sweat_smile:
