### ISSUE TITLE
Inconsistent warnings

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#61]
- Raised by #7 
- Ralphc compiler related.

# Issue 

Warning are inconsistent over multiple compilation runs. 

# Repreduce

Invoke save on `review.ral` displays the 3 warning messages.

![image](https://github.com/alephium/ralph-lsp/assets/1773953/25ad6aba-3d8b-4a0c-a737-ec58445f9bb2)

Invoking save on `abstract.ral` clears one of them. 

![image](https://github.com/alephium/ralph-lsp/assets/1773953/e35764f1-f6c9-4e1f-bcdf-a772b73b0ef9)

# Test log

`CompilerAccess` is receiving the correct data

Open `review.ral` returns the following warnings

> didOpen. fileURI: file:///Users/simerplaha/VSCodeProjects/ralph-test/contract/review.ral. code.isDefined: true
Contracts received: Foo2, Foo1, MyScript, Action, Math, Review, INFT, INFTCollection
Found unused fields in Foo2: foo1
No external caller check for function "Foo1.foo1". Please use "checkCaller!(...)" in the function or its callees, or disable it with "@using(checkExternalCaller = false)".
Found unused variables in Review: foo.token
No external caller check for function "Review.foo". Please use "checkCaller!(...)" in the function or its callees, or disable it with "@using(checkExternalCaller = false)".

Open `abstract.ral` returns the following warnings

> didOpen. fileURI: file:///Users/simerplaha/VSCodeProjects/ralph-test/contract/abstract.ral. code.isDefined: true
Contracts received: Foo2, Foo1, MyScript, Action, Math, Review, INFT, INFTCollection
Found unused fields in Foo2: foo1
Found unused variables in Review: foo.token 

Both calls are getting the same contracts so the output should be the same, but the warnings returned are not the same. I'm assuming this is an issue for ralphc. But requires more testing.

**Comment by simerplaha** [comment]
Inconsistent warnings occur when reusing Ralphc's parsed AST for compilation a second time. I'm assuming that's because the parsed AST gets mutated during compilation.

For example, in the following test, using the same parsed AST on the same code will result 2 warnings for the first run and 1 warning for the second run.

<details>
<summary>Test code</summary>

```scala
val contract =
  """
    |Contract MyContract(interface: MyInterface) {
    |  pub fn getBool() -> Bool {
    |    return interface.getBool()
    |  }
    |}
    |""".stripMargin

val interface =
  """
    |Interface MyInterface {
    |   pub fn getBool() -> Bool
    |}
    |""".stripMargin

val script =
  """
    |TxScript MyScript(x: U256, y: U256) {
    |  assert!(x != y, 0)
    |
    |  fn boolean() -> Bool {
    |    return true
    |  }
    |}
    |""".stripMargin


def parseOne(code: String): Ast.ContractWithState = {
  val result =
    RalphCompilerAccess.parseContracts(code).value.statements.collect {
      case source: Tree.Source =>
        source.ast
    }

  result should have size 1
  result.head
}

def parseAll() = {
  val contractAst = parseOne(contract)
  val interfaceAst = parseOne(interface)
  val scriptAst = parseOne(script)

  Seq(contractAst, interfaceAst, scriptAst)
}

val parsedAST =
  parseAll()

val result1 =
  RalphCompilerAccess.compileContracts(
    contracts = parsedAST,
    options = CompilerOptions.Default
  ).value

val result1Warnings: Array[String] =
  result1._1.flatMap(_.warnings) ++
    result1._2.flatMap(_.warnings)

val result2 =
  RalphCompilerAccess.compileContracts(
    contracts = parsedAST, // using parseAll() resolves the issue
    options = CompilerOptions.Default
  ).value

val result2Warnings: Array[String] =
  result2._1.flatMap(_.warnings) ++
    result2._2.flatMap(_.warnings)

println("Result 1 warnings: Count " + result1Warnings.length)
result1Warnings foreach println

println("\nResult 2 warnings: Count " + result2Warnings.length)
result2Warnings foreach println
```

</details>

> Result 1 warnings: Count 2
  No external caller check for function "MyContract.getBool". Please use "checkCaller!(...)" in the function or its callees, or disable it with "@using(checkExternalCaller = false)".
  Private function "MyScript.boolean" is not used

>  Result 2 warnings: Count 1
  Private function "MyScript.boolean" is not used

This needs a solution because we don't unnecessarily want to run the parser on all source-code on each keystroke, which will increase response time.

**Comment by simerplaha** [comment]
# Updated the above test case for the latest ralphc version

```scala
package org.alephium.ralph.lsp.access.compiler.ast
import org.alephium.ralph.{Ast, CompilerOptions}
import org.alephium.ralph.lsp.access.compiler.RalphCompilerAccess
import org.scalatest.matchers.should.Matchers
import org.scalatest.EitherValues._
import org.scalatest.wordspec.AnyWordSpec
import java.net.URI

class Test extends AnyWordSpec with Matchers {

  "test" in {
    val testURI = URI.create("file:///a.txt")

    val contract =
      """
        |Contract MyContract(interface: MyInterface) {
        |  pub fn getBool() -> Bool {
        |    return interface.getBool()
        |  }
        |}
        |""".stripMargin

    val interface =
      """
        |Interface MyInterface {
        |   pub fn getBool() -> Bool
        |}
        |""".stripMargin

    val script =
      """
        |TxScript MyScript(x: U256, y: U256) {
        |  assert!(x != y, 0)
        |
        |  fn boolean() -> Bool {
        |    return true
        |  }
        |}
        |""".stripMargin

    def parseOne(code: String): Ast.ContractWithState = {
      val result =
        RalphCompilerAccess.parseContracts(testURI, code).value.statements.collect {
          case source: Tree.Source =>
            source.ast
        }

      result should have size 1
      result.head.left.value
    }

    def parseAll() = {
      val contractAst  = parseOne(contract)
      val interfaceAst = parseOne(interface)
      val scriptAst    = parseOne(script)

      Seq(contractAst, interfaceAst, scriptAst)
    }

    val parsedAST =
      parseAll()

    val result1 =
      RalphCompilerAccess
        .compileContracts(
          contracts = parsedAST,
          structs = Seq.empty,
          options = CompilerOptions.Default,
          workspaceErrorURI = testURI
        )
        .value

    val result1Warnings: Array[String] =
      result1._1.flatMap(_.warnings) ++
        result1._2.flatMap(_.warnings)

    val result2 =
      RalphCompilerAccess
        .compileContracts(
          contracts = parsedAST, // using parseAll() resolves the issue
          structs = Seq.empty,
          options = CompilerOptions.Default,
          workspaceErrorURI = testURI
        )
        .value

    val result2Warnings: Array[String] =
      result2._1.flatMap(_.warnings) ++
        result2._2.flatMap(_.warnings)

    println("Result 1 warnings: Count " + result1Warnings.length)
    result1Warnings foreach println

    println("\nResult 2 warnings: Count " + result2Warnings.length)
    result2Warnings foreach println
  }
}
```

**Comment by tdroxler** [comment]
Fixed in https://github.com/alephium/ralph-lsp/releases/tag/v0.1.19
