### ISSUE TITLE
Review VSCode plugin

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#67]
The actual code in [`extension.ts`](https://github.com/alephium/ralph-lsp/blob/334c1f9103c50730a43261135c24df0dcebd4d17/plugin-vscode/src/extension.ts) is only 40 lines of code, but the [plugin itself](https://github.com/alephium/ralph-lsp/tree/334c1f9103c50730a43261135c24df0dcebd4d17/plugin-vscode) contains 7 configuration files 😱 which is a bit crazy. I wonder if I've set this up incorrectly.

Be nice to have one of our experienced TypeScript devs to review the VSCode plugin before the release.

@tdroxler please advice.

**Comment by tdroxler** [comment]
@mvaivre I know you're super busy, but if you have some time at some point :) thxxx :kissing_heart:

**Comment by mvaivre** [comment]
Thanks for the ping! Will try this week!

**Comment by mvaivre** [comment]
I'm not familiar with plugin dev (ie. what should be in the .vscode folder), but based on what I see at the root I think it's (unfortunately) correct. Lots of boilerplate in this JS world..!

**Comment by simerplaha** [comment]
Thank you guys.

Closing this as resolved.
